name: Build

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Check
        run: cargo check

      - name: Luhn
        run: cargo luhn

      - name: Space age
        run: cargo age

      - name: Run Tests
        run: cargo test


